linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - bodyclose
    - contextcheck
    - nilerr
    - exportloopref

linters-settings:
  govet:
    enable-all: true
  gosec:
    excludes:
      - G104  # unhandled errors in deferred calls
  errcheck:
    check-type-assertions: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5

run:
  timeout: 5m
  go: "1.21"
